
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import ctypes

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from scripts import predict


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

ctypes.windll.shcore.SetProcessDpiAwareness(1)
window = Tk()

window.geometry("960x630")
window.configure(bg = "#44C7FF")


canvas = Canvas(
    window,
    bg = "#44C7FF",
    height = 630,
    width = 960,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    480.0,
    7.105427357601002e-15,
    960.0,
    630.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    540.0,
    72.0,
    anchor="nw",
    text="Ticket Allocation",
    fill="#666666",
    font=("Calibri Bold", 24 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    720.0,
    173.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F2F2F2",
    highlightthickness=0,
    font=("Calibri", 20 * -1)

)
entry_1.place(
    x=550.0,
    y=143.0,
    width=340.0,
    height=58.0
)

canvas.create_text(
    550.0,
    126.0,
    anchor="nw",
    text="Problem",
    fill="#666666",
    font=("Calibri Bold", 14 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    720.0,
    362.0,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#F2F2F2",
    highlightthickness=0,
    font=("Calibri", 20 * -1)

)
entry_2.place(
    x=550.0,
    y=242.0,
    width=340.0,
    height=238.0
)

canvas.create_text(
    550.0,
    228.0,
    anchor="nw",
    text="Description",
    fill="#666666",
    font=("Calibri Bold", 14 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: predict(entry_1,entry_2),
    relief="flat"
)
button_1.place(
    x=645.0,
    y=507.0,
    width=150.0,
    height=50.0
)

canvas.create_text(
    40.0,
    286.0,
    anchor="nw",
    text="Welcome to the\nAutomatic Ticketing system",
    fill="#FFFFFF",
    font=("Calibri Bold", 24 * -1)
)
window.resizable(False, False)
window.mainloop()
